name: Analyse RH Automatisée

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyse-rh:
    runs-on: ubuntu-latest

    steps:
    - name: 🔄 Cloner le dépôt
      uses: actions/checkout@v3

    - name: 🐍 Installer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: 📦 Installer les dépendances
      run: |
        pip install --upgrade pip
        pip install pandas mysql-connector-python matplotlib seaborn

    - name: ▶️ Exécuter le script RH
      run: python analyse_rh_mysql_pandas.py
