name: Analyse RH MySQL

on:
  push:
    branches:
      - main

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Installer les dépendances
        run: |
          pip install -r requirements.txt

      - name: Exécuter le script d'analyse RH
        run: python scripts_python/analyse_rh_mysql_pandas.py
